# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rozkurcz/Pobrane/CLion/clion-2019.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/rozkurcz/Pobrane/CLion/clion-2019.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rozkurcz/Dokumenty/c/game1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rozkurcz/Dokumenty/c/game1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rozkurcz/Pobrane/CLion/clion-2019.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/rozkurcz/Pobrane/CLion/clion-2019.3/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rozkurcz/Dokumenty/c/game1/CMakeFiles /home/rozkurcz/Dokumenty/c/game1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rozkurcz/Dokumenty/c/game1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fullGame

# Build rule for target.
fullGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fullGame
.PHONY : fullGame

# fast build rule for target.
fullGame/fast:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/build
.PHONY : fullGame/fast

gameWindow.o: gameWindow.c.o

.PHONY : gameWindow.o

# target to build an object file
gameWindow.c.o:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/gameWindow.c.o
.PHONY : gameWindow.c.o

gameWindow.i: gameWindow.c.i

.PHONY : gameWindow.i

# target to preprocess a source file
gameWindow.c.i:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/gameWindow.c.i
.PHONY : gameWindow.c.i

gameWindow.s: gameWindow.c.s

.PHONY : gameWindow.s

# target to generate assembly for a file
gameWindow.c.s:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/gameWindow.c.s
.PHONY : gameWindow.c.s

geometry.o: geometry.c.o

.PHONY : geometry.o

# target to build an object file
geometry.c.o:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/geometry.c.o
.PHONY : geometry.c.o

geometry.i: geometry.c.i

.PHONY : geometry.i

# target to preprocess a source file
geometry.c.i:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/geometry.c.i
.PHONY : geometry.c.i

geometry.s: geometry.c.s

.PHONY : geometry.s

# target to generate assembly for a file
geometry.c.s:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/geometry.c.s
.PHONY : geometry.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/main.c.s
.PHONY : main.c.s

welcomeWindow.o: welcomeWindow.c.o

.PHONY : welcomeWindow.o

# target to build an object file
welcomeWindow.c.o:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/welcomeWindow.c.o
.PHONY : welcomeWindow.c.o

welcomeWindow.i: welcomeWindow.c.i

.PHONY : welcomeWindow.i

# target to preprocess a source file
welcomeWindow.c.i:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/welcomeWindow.c.i
.PHONY : welcomeWindow.c.i

welcomeWindow.s: welcomeWindow.c.s

.PHONY : welcomeWindow.s

# target to generate assembly for a file
welcomeWindow.c.s:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/welcomeWindow.c.s
.PHONY : welcomeWindow.c.s

windowManager.o: windowManager.c.o

.PHONY : windowManager.o

# target to build an object file
windowManager.c.o:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/windowManager.c.o
.PHONY : windowManager.c.o

windowManager.i: windowManager.c.i

.PHONY : windowManager.i

# target to preprocess a source file
windowManager.c.i:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/windowManager.c.i
.PHONY : windowManager.c.i

windowManager.s: windowManager.c.s

.PHONY : windowManager.s

# target to generate assembly for a file
windowManager.c.s:
	$(MAKE) -f CMakeFiles/fullGame.dir/build.make CMakeFiles/fullGame.dir/windowManager.c.s
.PHONY : windowManager.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... fullGame"
	@echo "... edit_cache"
	@echo "... gameWindow.o"
	@echo "... gameWindow.i"
	@echo "... gameWindow.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... welcomeWindow.o"
	@echo "... welcomeWindow.i"
	@echo "... welcomeWindow.s"
	@echo "... windowManager.o"
	@echo "... windowManager.i"
	@echo "... windowManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

